spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/sshrike
    username: sshrike
    password: sshrike
  cache:
    type: redis
    host: localhost
    port: 6379
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  security:
    user:
      name: user
      password: password

amazon:
  s3:
    accessKey: AKIAIYPRJ33PIEUVBHIQ
    secretKey: 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